name          'dgu_solr'
version       '0.0.1'
source        'UNKNOWN'
author        'Silex Consulting'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'
